hdfs:
  addr: hdfs://master:8020
  reposPath: /gift/repositories


chatGPT:
  host: https://api.openai.com
  model: gpt-3.5-turbo-16k
  apiKeys:
    - sk-xxx_1
    - ...
    - sk-xxx_n


xingHou:
  hostUrl: https://spark-api.xf-yun.com/v3.1/chat
  appid: xxx
  apiSecret: xxx
  apiKey: xxx


chatGLM:
  hostUrl: https://open.bigmodel.cn/api/paas/v3/model-api/text_embedding/invoke
  apiKey: xxx


kafka:
  hostUrl: kafka:9092


elasticsearch:
  hostUrl: http://elasticsearch:9200
