# 应用服务 WEB 访问端口
server:
  port: 8087
#Druid德鲁伊数据池
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver   #TODO 数据表未知
      url: jdbc:mysql://139.9.65.13:23306/test?useSSL=false&serverTimezone=UTC
      username: root
      password: root
  data:
    elasticsearch:
      client:
        reactive:
          connection-timeout: 10000
#  elasticsearch:
#    rest:
#      uris: http://elasticsearch:9200 #ES服务器位置
#mp设置表
mybatis-plus:
  global-config:
    db-config:
      table-prefix: hadoop_    #TODO 数据库连接表未知,本地测试数据表hadoop_project
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method <init>()V not found


